[package]
name = "spell"
version = "0.1.0"
authors = ["uxiun <teppeiito0905@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slab_tree = "0.3.2"